GT-134 Add annotation to change architecture
arangodb/kube-arangodb pull request #1107
Opened 2022-09-14 09:12 UTC by jwierzbo

2022-09-14 16:46 UTC, nikita-vanyasin approved these changes
LGTM. But are there any integration tests for this feature?

2022-09-15 10:53 UTC, jwierzbo commented
@nikita-vanyasin https://github.com/arangodb/kube-arangodb-test/pull/130/files

2022-10-03 07:43 UTC, ajanikow requested changes

2022-10-03 07:43 UTC, ajanikow commented on pkg/deployment/reconcile/action_set_current_arch.go
> +//
File name should match action name (validator will ensure it soon)

2022-10-03 07:43 UTC, ajanikow commented on pkg/deployment/rotation/check.go
> +	SilentRotation       // Propagate changes without restart
Add comment in go format

2022-10-03 08:08 UTC, adam-janikowski approved these changes

2022-10-03 08:21 UTC, merged