GT-313 Fix for ContextExceeded error during backup upload
arangodb/kube-arangodb pull request #1227
Opened 2023-01-11 12:54 UTC by jwierzbo

2023-01-11 13:04 UTC, nikita-vanyasin approved these changes

2023-01-11 14:20 UTC, informalict approved these changes
lgtm

2023-01-11 16:50 UTC, ajanikow requested changes
What is root cause of this issue?

Backup upload start is atomic operation which just start task behind on ArangoD side. Do not know why timeout should be increased (Upload will retry anyway)

2023-03-06 08:19 UTC, ajanikow commented
@jwierzbo Fix or close this PR

2023-03-06 08:53 UTC, closed without merging