GT-198 Cleanout calculation - picks members with the lowest number of…
arangodb/kube-arangodb pull request #1261
Opened 2023-03-01 11:58 UTC by jwierzbo

… shards

2023-03-01 14:30 UTC, nikita-vanyasin approved these changes

2023-03-01 14:30 UTC, nikita-vanyasin commented on pkg/deployment/agency/state.go
> +func (s State) ShardsByDbServers() map[Server]int {
```suggestion
func (s State) ShardsByDBServers() map[Server]int {
```

2023-03-06 05:27 UTC, informalict approved these changes
lgtm

2023-03-06 08:17 UTC, ajanikow requested changes

2023-03-06 08:17 UTC, ajanikow commented on pkg/apis/deployment/v1/member_status.go
> +	// RecentTerminations holds the times when this member was recently terminated.
Synchronize versions

2023-03-06 14:56 UTC, ajanikow approved these changes

2023-03-06 14:56 UTC, merged