GT-350 Backup lifetime - remove Backup once its lifetime has been reached
arangodb/kube-arangodb pull request #1262
Opened 2023-03-03 15:06 UTC by jwierzbo

2023-03-06 08:18 UTC, ajanikow requested changes

2023-03-06 08:18 UTC, ajanikow commented on pkg/apis/backup/v1/backup_spec.go
> +
Synchronize

2023-03-06 08:18 UTC, ajanikow commented on pkg/handlers/backup/state_ready.go
> +	if backup.Spec.Lifetime != "" {
Any test?

2023-03-06 08:18 UTC, ajanikow commented on pkg/apis/backup/v1/backup_spec.go
> +	Lifetime string `json:"lifetime,omitempty"`
Try meta.Duration instead of custom parser

2023-03-06 12:37 UTC, jwierzbo commented
Tests: https://github.com/arangodb/kube-arangodb-test/pull/164/files

2023-03-06 17:28 UTC, jwierzbo commented
http://a449ed7c695a44a0faa7c64adce736b0-340255436.eu-central-1.elb.amazonaws.com/job/OperatorTestRun/923/parameters/

2023-07-17 12:43 UTC, ajanikow approved these changes

2023-07-17 12:43 UTC, merged