GT-402 Fix for ArangoTask list error
arangodb/kube-arangodb pull request #1289
Opened 2023-04-12 11:20 UTC by jwierzbo

2023-04-12 11:47 UTC, nikita-vanyasin approved these changes

2023-04-14 11:09 UTC, ajanikow requested changes

2023-04-14 11:09 UTC, ajanikow commented on chart/kube-arangodb/crds/database-task.yaml
> +      - arangotask
Not needed

2023-04-17 01:38 UTC, fullc0de commented
Hello @jwierzbo 

Is this change also related to the following error message I ran into my k8s monitoring?
`
E0417 01:26:56.058194       1 reflector.go:138] pkg/generated/informers/externalversions/factory.go:125: Failed to watch *v1.ArangoTask: failed to list *v1.ArangoTask: the server could not find the requested resource (get arangotasks.database.arangodb.com)
`

Thank you!

2023-04-17 03:14 UTC, ajanikow commented
> Hello @jwierzbo
> 
> Is this change also related to the following error message I ran into my k8s monitoring? `E0417 01:26:56.058194 1 reflector.go:138] pkg/generated/informers/externalversions/factory.go:125: Failed to watch *v1.ArangoTask: failed to list *v1.ArangoTask: the server could not find the requested resource (get arangotasks.database.arangodb.com)`
> 
> Thank you!

Yes, it wil fix this misleading error message.

2023-04-17 03:14 UTC, ajanikow approved these changes

2023-04-17 03:15 UTC, merged