[Improvement] GT-248 restart non-scheduled pod
arangodb/kube-arangodb pull request #1376
Opened 2023-08-04 14:01 UTC by nikita-vanyasin

2023-08-07 11:47 UTC, jwierzbo approved these changes

2023-09-15 07:19 UTC, ajanikow requested changes

2023-09-15 07:19 UTC, ajanikow commented on pkg/deployment/reconcile/plan_builder_member_pod_scheduling_failure.go
> +		if r.isSchedulingParametersChanged(renderedPod.Spec, m.Member, context) {
If currently terminating (ConditionTypeTerminating), skip

2023-09-15 07:19 UTC, ajanikow commented on CHANGELOG.md
> +- (Improvement) Restart pod if it could not be scheduled and related scheduling parameters changed
Single CHANGELOG Line

2023-09-15 07:53 UTC, nikita-vanyasin commented on CHANGELOG.md
> +- (Improvement) Restart pod if it could not be scheduled and related scheduling parameters changed
done

2023-09-15 07:53 UTC, nikita-vanyasin commented on pkg/deployment/reconcile/plan_builder_member_pod_scheduling_failure.go
> +		if r.isSchedulingParametersChanged(renderedPod.Spec, m.Member, context) {
done

2023-09-15 08:19 UTC, ajanikow approved these changes

2023-09-15 08:19 UTC, merged