GT-525 License Manager for ML Deployment
arangodb/kube-arangodb pull request #1501
Opened 2023-11-22 19:22 UTC by jwierzbo

2023-11-22 19:37 UTC, nikita-vanyasin approved these changes

2023-11-22 19:37 UTC, nikita-vanyasin commented on pkg/license/license.go
> +func (f Feature) IsContained(features []Feature) bool {
```suggestion
func (f Feature) In(features []Feature) bool {
```

2023-11-27 08:30 UTC, ajanikow requested changes

2023-11-27 08:30 UTC, ajanikow commented on pkg/license/loader_test.go
> +type MockLoader struct {
Not used anywhere?

2023-11-27 21:28 UTC, jwierzbo commented on pkg/license/loader_test.go
> +type MockLoader struct {
in tests

2023-11-29 09:19 UTC, merged