Jobs templates
arangodb/kube-arangodb pull request #1539
Opened 2023-12-13 14:09 UTC by jwierzbo

2023-12-15 07:58 UTC, nikita-vanyasin approved these changes

2023-12-15 07:58 UTC, nikita-vanyasin commented on pkg/apis/ml/v1alpha1/extension_spec_job.go
> +		if err := template.Validate(); err != nil {
No need to check for errors - `shared.WithErrors` will combine only non-nil entries anyway

2023-12-15 10:01 UTC, ajanikow requested changes

2023-12-15 10:01 UTC, ajanikow commented on pkg/apis/ml/v1alpha1/extension_spec_job.go
> +	Prediction map[string]*ArangoMLExtensionTemplateSpec `json:"prediction,omitempty"`
Do not use map, use CPU/GPU fields instead

2023-12-18 13:10 UTC, ajanikow commented on pkg/apis/ml/v1alpha1/extension_conditions.go
> +	MLExtensionFoundCondition              api.ConditionType = "MLExtensionFound"
To ExtensionFoundCondition + move to conditions.go

2023-12-18 13:15 UTC, ajanikow commented on pkg/apis/ml/v1alpha1/extension_spec_job.go
> +type ArangoMLExtensionTemplateSpec struct {
ArangoMLExtensionTemplateSpec -> Może ArangoMLExtensionPodTemplate ?

2023-12-18 14:50 UTC, ajanikow approved these changes

2023-12-18 14:51 UTC, merged