Use new arangosync-client
arangodb/kube-arangodb pull request #767
Opened 2021-07-28 12:38 UTC by informalict

2021-08-05 21:07 UTC, ajanikow approved these changes

2021-08-05 21:08 UTC, ajanikow requested changes

2021-08-05 21:08 UTC, ajanikow commented on CHANGELOG.md
> +- Update 'github.com/arangodb/arangosync-client' dependency to v0.7.0
Please, move it under master section

2021-08-06 05:21 UTC, informalict commented on CHANGELOG.md
> +- Update 'github.com/arangodb/arangosync-client' dependency to v0.7.0
changed

2021-08-10 14:24 UTC, ajanikow approved these changes

2021-08-10 14:24 UTC, merged