Check if the server is cleaned out
arangodb/kube-arangodb pull request #775
Opened 2021-08-19 07:43 UTC by informalict

2021-08-23 14:26 UTC, ajanikow requested changes

2021-08-23 14:26 UTC, ajanikow commented on pkg/apis/deployment/v1/plan.go
> +	ActionTypeSetMemberCondition ActionType = "SetMemberCondition"
Add it as HighPriority in line 52

2021-08-23 14:26 UTC, ajanikow commented on pkg/apis/deployment/v2alpha1/plan.go
> +	ActionTypeSetMemberCondition ActionType = "SetMemberCondition"
run make synchronize-...

2021-08-23 14:26 UTC, ajanikow commented on pkg/deployment/reconcile/action_set_member_condition.go
> +func (a actionSetMemberCondition) Priority() api.ActionPriority {
Why? Check comments

2021-08-23 17:56 UTC, informalict commented on pkg/apis/deployment/v1/plan.go
> +	ActionTypeSetMemberCondition ActionType = "SetMemberCondition"
changed

2021-08-23 17:56 UTC, informalict commented on pkg/apis/deployment/v2alpha1/plan.go
> +	ActionTypeSetMemberCondition ActionType = "SetMemberCondition"
launched

2021-08-23 17:56 UTC, informalict commented on pkg/deployment/reconcile/action_set_member_condition.go
> +func (a actionSetMemberCondition) Priority() api.ActionPriority {
removed

2021-08-24 00:07 UTC, ajanikow approved these changes

2021-08-24 00:07 UTC, merged