Parameterize K8s Deployment's Tolerations in helm chart
arangodb/kube-arangodb pull request #878
Opened 2022-01-04 15:56 UTC by jwierzbo

2022-01-04 17:57 UTC, ajanikow requested changes
Missing doc: https://github.com/arangodb/kube-arangodb/blob/master/chart/kube-arangodb/README.md

2022-01-05 00:03 UTC, ajanikow requested changes

2022-01-05 00:03 UTC, ajanikow commented on chart/kube-arangodb/README.md
> +Tolerations:
Tolerations -> tolerations

2022-01-05 00:03 UTC, ajanikow commented on chart/kube-arangodb/README.md
> +operator: Exists
Indent?

2022-01-05 08:26 UTC, informalict approved these changes
LGTM

2022-01-05 15:55 UTC, informalict approved these changes
LGTM

2022-01-10 09:04 UTC, ajanikow approved these changes

2022-01-10 09:04 UTC, merged